version: "3.7"
services:
  # Interactive shell for running commands
  nrdk:
    build: ./dev
    container_name: nrdk
    depends_on:
      watcher:
        condition: service_healthy
    entrypoint: ["bash"]
    hostname: nrdk
    restart: always
    # stdin_open (run -i) and tty (run -t) for interactive shell
    stdin_open: true
    tty: true
    volumes_from:
      - watcher
    working_dir: "/app"

  # Run npm install, build and watch
  watcher:
    build: ./dev
    container_name: nrdk-watcher
    entrypoint: ["bash", "-c", "npm run watcher"]
    healthcheck:
      interval: 5s
      retries: 10
      test: ["CMD", "bash", "-c", "./bin/run", version"]
      timeout: 5s
    hostname: nrdk-watcher
    restart: always
    # Mount repo to /app, but not node_modules
    volumes:
      - "./:/app"
      - "/app/node_modules"
    working_dir: "/app"
