version: "3.7"
services:
  # Interactive shell for running commands
  nrdk:
    build: .
    container_name: nrdk
    entrypoint: ["bash", "-c", "npm ci && /bin/bash"]
    hostname: nrdk
    restart: always
    # stdin_open (run -i) and tty (run -t) for interactive shell
    stdin_open: true
    tty: true
    # Mount repo to /app, but not node_modules
    volumes:
      - "/app/node_modules"
      - "../:/app"
    working_dir: "/app"
