name: Move assigned to In Progress
on:
  issues:
    types:
      - assigned
jobs:
  move-assigned-card:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.3.0
        with:
          project: Release 0.1.0
          column: In Progress
          repo-token: ${{ secrets.PROJECT_AUTOMATION }}
 