# workflow based on https://www.geekytidbits.com/github-actions-version-and-release-to-npm/

name: Publish to npm Registry

on:
  workflow_dispatch: 

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        
      - name: install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      
      - name: continuous integration package install
        run: npm ci

      - name: increment version
        run: |
          npm set //registry.npmjs.org/:_authToken $NODE_AUTH_TOKEN
          npm --no-git-tag-version version prerelease 
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: commit new version
        uses: EndBug/add-and-commit@v7.2.1
        with:
          add: '["package.json", "package-lock.json", "README.md"]'
          author_name: Derek Roberts
          author_email: derek.roberts@gmail.com
          message: 'Release: cut a new release'
          pull_stragegy: 'NO-PULL'

      - name: publish
        run: |
          npm set //registry.npmjs.org/:_authToken $NODE_AUTH_TOKEN
          npm publish --access public
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
